### ISSUE TITLE
Returning all columns of tables

### ISSUE THREAD

**Issue by YaguraStation** [cbbrowne/autodoc#18]
Maybe I've missed an option, but is there a way to return _all_ columns of tables? 

PS: Thanks for the great tool.

**Comment by cbbrowne** [comment]
I kinda thought we did?

The HTML output certainly has table columns.

The exception that comes to mind is that we probably don't capture the oid column, but PostgreSQL switched from having oids by default to requiring pretty special intervention to have them a mighty long time ago.  Can you be more specific as to what might be missing?
