### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by nelsonic** [cbbrowne/autodoc#2]
Hi @cbbrowne is this project still being developed/maintained?
Are there docs or a usage example?

**Comment by cbbrowne** [comment]
It's certainly still being used; I put it up here in view that my employer was using it internally inside some work processes, and we wanted to make sure the code was handy in a public place.

There's a manual page; see https://github.com/cbbrowne/autodoc/blob/master/postgresql_autodoc.1.in

**Comment by cbbrowne** [comment]
Separately, someone recommended a patch to improve the readme that is on the "front page" for GitHub; I accepted that as seeming useful.
