### ISSUE TITLE
diagram

### ISSUE THREAD

**Issue by srulikuk** [cbbrowne/autodoc#20]
Thanks for a fast easy to use no mess tool!!
I am exporting to dia (and zigzag.dia) but the result is all tables stacked on top of each other (~90 tables) how can i spread them out so i can see the full picture?

**Comment by srulikuk** [comment]
I see now in the options section 
```
It does not do any automated layout, so making the diagram usable would require manual work, so this is often not terribly useful.
```
:-(
is there no automated way to do the layout?

**Comment by cbbrowne** [comment]
The straight answer:  There is NOW no automated way to do the layout.  

That doesn't mean it's impossible, however it seems like a fairly difficult thing to do.

GraphViz (which is what is used to process some of the other forms) does automated layouts, but in terms of turning that into an automatic process for rewriting a dia file, that sure seems like a complicated road to take.

I recall there being some dia-like tool on MacOS that used an embedded GraphViz to automatically rebalance layouts of diagrams.  OmniGraffle, I think?

I wonder if there's merit to contacting the Dia developers, and asking them if they have looked into GraphViz integration?  It would be useful there for many things other than just PostgreSQL AutoDoc
