### ISSUE TITLE
Change url from http://www.rbt.ca/autodoc to  https://github.com/cbbrowne/autodoc ?

### ISSUE THREAD

**Issue by hasorli** [cbbrowne/autodoc#8]
Current : 
<p class="w3ref">Generated by <a href="http://www.rbt.ca/autodoc/">PostgreSQL Autodoc</a></p>

New : 
<p class="w3ref">Generated by <a href="https://github.com/cbbrowne/autodoc">PostgreSQL Autodoc</a></p>

Should this be done? There is no content at the old url (rbc.ca).

**Comment by cbbrowne** [comment]
Hmm.  Looks like Rod's web site is less-well-populated than it used to be.

I'll leave it for now; I'll probably see him at PGCon in Ottawa; should check then...

**Comment by cbbrowne** [comment]
The lack of content has persisted, so changing the pointer to the GitHub repo.

Commit efbe6a29d0ff381deb7849652e56889842a69407
